### ISSUE TITLE
server rejected meta data. status: 400

### ISSUE THREAD

**Issue by Tinche** [vmprof/vmprof-server#24]
While uploading a trace. CPython 3.6.1, macOS El Capitan. The trace is much smaller than 100 MB (~28 MB).

```
> python -m vmprof.upload --web-auth .. output-small.log
Uploading to http://vmprof.com...
 => Uploading the cpu profile...
/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmshare/service.py:96: UserWarning: WARNING: vmprof.com limits the compressed profile file to 100 MBs. The upload might fail!

  warnings.warn("WARNING: vmprof.com limits the "
server rejected meta data. status: 400, msg: '["could not extract meta data for feb6a5e5-5a0a-43cd-8069-99daf1fe090e. exception: [Errno 111] Connection refused"]'
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmprof/upload.py", line 22, in <module>
    main()
  File "/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmprof/upload.py", line 19, in main
    'VM': interpname })
  File "/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmshare/service.py", line 124, in post
    Service.FILE_CPU_PROFILE, compress=False)
  File "/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmshare/service.py", line 106, in post_file
    self.stop_if_error_occured(response)
  File "/Users/ttvrtkovic/workspace/ngs-worker-ct2/.venv/lib/python3.6/site-packages/vmshare/service.py", line 73, in stop_if_error_occured
    raise ServiceException()
vmshare.service.ServiceException
```

**Comment by planrich** [comment]
Could you retry and share the profile if it does not work? I have updated the server's vmprof package and restarted the cache service. that might be an issue for raising the exception: "could not extract meta data for feb6a5e5-5a0a-43cd-8069-99daf1fe090e. exception: [Errno 111] Connection refused"

**Comment by Tinche** [comment]
Thanks, it's working now! I've successfully uploaded at http://vmprof.com/#/271a4d89-0f8b-46b3-821f-7e2c9c130104.

**Comment by nctl144** [comment]
Hey guys, I also got the same error today when I tried uploading my vmprof result on the server. Can you guys please help me with that? Thank you 😄

**Comment by kolypto** [comment]
Same issue. My first profile got rejected
